name: Build and Release
run-name: ${{ gitea.actor }} build 🚀

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          mkdir -p assets/resources
          printf "%s" "${{ secrets.ENV_FILE }}" > assets/resources/.env

      - name: Deploy to Container
        run: |
          docker compose --env-file ./assets/resources/.env up -d --build --remove-orphans